from pydantic import ValidationError as PydanticValidationError
from devai.core.models import DeploymentPlan
from devai.core.exceptions import ValidationError

class SchemaValidator:
    """
    Deterministic Validation Layer.
    Ensures that any plan generated by the AI conforms to the strict schema
    and any defined organizational security policies.
    """
    
    def validate_plan(self, plan_json_or_dict: dict | str) -> DeploymentPlan:
        """Validates raw output and returns a strongly-typed DeploymentPlan."""
        try:
            if isinstance(plan_json_or_dict, str):
                return DeploymentPlan.model_validate_json(plan_json_or_dict)
            else:
                return DeploymentPlan.model_validate(plan_json_or_dict)
        except PydanticValidationError as e:
            raise ValidationError(f"Plan validation failed: {str(e)}")
            
    def enforce_security_policies(self, plan: DeploymentPlan):
        """
        Example of deterministic security policies.
        Ensures the AI did not hallucinate unsafe configurations.
        """
        if not plan.resources:
            raise ValidationError("Plan contains no resources to deploy.")
            
        known_types = {"docker_container", "s3_bucket", "ec2_instance", "kubernetes_deployment"}
            
        for resource in plan.resources:
            if resource.type not in known_types:
                raise ValidationError(f"Security Policy Violation: Resource type '{resource.type}' is not supported or allowed.")
                
            if resource.type == "s3_bucket":
                if resource.properties.get("public_access", False):
                    raise ValidationError(f"Security Policy Violation: Resource {resource.name} has public_access enabled.")
                    
            if resource.type == "docker_container":
                if "image" not in resource.properties:
                    raise ValidationError(f"Configuration Error: Docker container {resource.name} missing 'image' property.")
                image = resource.properties["image"]
                if ":latest" in image:
                    # An example of a soft warning vs a hard error could be added here
                    pass
