from typing import Any

from pydantic import ValidationError as PydanticValidationError
from devai.core.models import DeploymentPlan
from devai.core.exceptions import ValidationError


class SchemaValidator:
    """
    Deterministic Validation Layer.
    Ensures that any plan generated by the AI conforms to the strict schema
    and any defined organizational security policies.
    """

    BLOCKED_PROPERTY_KEYS = {
        "command",
        "commands",
        "shell",
        "script",
        "raw_command",
        "kubectl",
        "docker_run",
        "ssh_command",
    }

    def validate_plan(self, plan_json_or_dict: dict | str) -> DeploymentPlan:
        """Validates raw output and returns a strongly-typed DeploymentPlan."""
        try:
            if isinstance(plan_json_or_dict, str):
                stripped = plan_json_or_dict.strip()
                if not stripped.startswith("{"):
                    raise ValidationError("Planner output must be a single JSON object.")
                plan = DeploymentPlan.model_validate_json(stripped)
            else:
                plan = DeploymentPlan.model_validate(plan_json_or_dict)
        except PydanticValidationError as e:
            raise ValidationError(f"Plan validation failed: {str(e)}")

        self._reject_direct_command_fields(plan.model_dump())
        self._validate_resource_requirements(plan)
        return plan

    def enforce_security_policies(self, plan: DeploymentPlan):
        """
        Example of deterministic security policies.
        Ensures the AI did not hallucinate unsafe configurations.
        """
        if not plan.resources:
            raise ValidationError("Plan contains no resources to deploy.")

        valid_types = [
            "docker_container",
            "vps_server",
            "multi_service_deployment",
            "s3_bucket",
            "ec2_instance",
            "kubernetes_deployment",
        ]

        for resource in plan.resources:
            if resource.type not in valid_types:
                raise ValidationError(
                    f"Security Policy Violation: Resource type '{resource.type}' is not supported or allowed."
                )

            if resource.type == "s3_bucket" and resource.properties.get("public_access", False):
                raise ValidationError(
                    f"Security Policy Violation: Resource {resource.name} has public_access enabled."
                )

            if resource.type == "docker_container":
                if "image" not in resource.properties:
                    raise ValidationError(
                        f"Configuration Error: Docker container {resource.name} missing 'image' property."
                    )
                image = resource.properties["image"]
                if ":latest" in image:
                    pass

    def _reject_direct_command_fields(self, value: Any, path: str = "plan") -> None:
        if isinstance(value, dict):
            for key, nested_value in value.items():
                normalized_key = str(key).lower()
                if normalized_key in self.BLOCKED_PROPERTY_KEYS:
                    raise ValidationError(
                        f"Security Policy Violation: direct command field '{path}.{key}' is not allowed. "
                        "AI must emit structured actions only."
                    )
                self._reject_direct_command_fields(nested_value, f"{path}.{key}")
        elif isinstance(value, list):
            for index, item in enumerate(value):
                self._reject_direct_command_fields(item, f"{path}[{index}]")

    def _validate_resource_requirements(self, plan: DeploymentPlan) -> None:
        if not plan.resources:
            raise ValidationError("Plan contains no resources to deploy.")

        for resource in plan.resources:
            if resource.type == "docker_container" and "image" not in resource.properties:
                raise ValidationError(f"Docker container '{resource.name}' is missing an image.")

            if resource.type == "multi_service_deployment":
                server = resource.properties.get("server")
                services = resource.properties.get("services")
                if not server:
                    raise ValidationError(
                        f"Multi-service deployment '{resource.name}' must target a named server."
                    )
                if not isinstance(services, list) or not services:
                    raise ValidationError(
                        f"Multi-service deployment '{resource.name}' must define at least one service."
                    )
                for service in services:
                    if not isinstance(service, dict):
                        raise ValidationError(
                            f"Service entries for '{resource.name}' must be JSON objects."
                        )
                    if "name" not in service or "image" not in service:
                        raise ValidationError(
                            f"Each service in '{resource.name}' must include 'name' and 'image'."
                        )

            if resource.type == "vps_server":
                forbidden = self.BLOCKED_PROPERTY_KEYS.intersection(
                    {str(key).lower() for key in resource.properties.keys()}
                )
                if forbidden:
                    keys = ", ".join(sorted(forbidden))
                    raise ValidationError(
                        f"VPS server resource '{resource.name}' includes forbidden command-style properties: {keys}"
                    )
